# Generated by Django 4.2.13 on 2026-05-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
